### ISSUE TITLE
[11/17] GDSC 팀프로젝트 1차 회의

### ISSUE THREAD

**Issue by seojinJeon** [Google-Developer-Student-Clubs-TUK/2024-Flutter-Project-MyLio#13]
## Task
- [x]  기능구현을 할 수 있는 라이브러리 찾아오기→ALL
- [x]  깃허브 초대→서진
- [x]  로그인 화면 만들기, 회원가입→승원
- [x]  스프링-플러터 연동→나혜
- [x]  DB→수혁,성현
- [x]  도메인 구현 → 수혁, 성현
- [x]  api→수혁,성현
- [x]  aws→수혁,성현

## 정기회의
- 전체: 토요일 저녁 10시
- 프론트엔드: 일요일 저녁 9시 반

## Figma
https://www.figma.com/design/El8f5anNMWbqTD3gWe65xR/MyLio?node-id=0-1&t=Vz2yXheT8xDGIbE1-1

## When2meet
https://www.when2meet.com/?27608751-QQOnJ
